NaiveWebServer::ServerGateway
Connection NaiveWebServer.ServerGateway.connection
Referenced by NaiveWebServer.ServerGateway.ServerGateway.
Dispatcher NaiveWebServer.ServerGateway.dispatcher
Referenced by NaiveWebServer.ServerGateway.ServerGateway.
NaiveWebServer.ServerGateway.ServerGateway(Connection connection, Dispatcher dispatcher)
References NaiveWebServer.ServerGateway.connection, NaiveWebServer.ServerGateway.dispatcher, NaiveWebServer.ServerGateway.HandleNewSocketConnection.
void NaiveWebServer.ServerGateway.Enable()
void NaiveWebServer.ServerGateway.Disable()
void NaiveWebServer.ServerGateway.HandleNewSocketConnection(TcpClient clientSocket)
References NaiveWebServer.ServerGateway.ForwardSocketToDispatcher, NaiveWebServer.ServerGateway.NewSocketConnectionToHttpContext.
Referenced by NaiveWebServer.ServerGateway.ServerGateway.
HttpContext NaiveWebServer.ServerGateway.NewSocketConnectionToHttpContext(TcpClient clientSocket)
Referenced by NaiveWebServer.ServerGateway.HandleNewSocketConnection.
void NaiveWebServer.ServerGateway.ForwardSocketToDispatcher(HttpContext httpContext)
Referenced by NaiveWebServer.ServerGateway.HandleNewSocketConnection.